# Generated by Django 2.0.6 on 2018-06-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20180616_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplieraccount',
            options={},
        ),
    ]
