# Generated by Django 2.0.6 on 2018-06-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_thumbnail_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='image',
            new_name='media',
        ),
    ]
