# Generated by Django 2.0.6 on 2018-06-16 22:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180616_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='media',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.models.media_location, width_field='width_field'),
        ),
    ]
