# Generated by Django 2.0.6 on 2018-06-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.ForeignKey(default='Strada Dreptatii', on_delete=django.db.models.deletion.CASCADE, to='core.Venue'),
        ),
    ]
