# Generated by Django 2.0.6 on 2018-06-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
    ]
